# Generated by Django 3.2 on 2021-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
