# Generated by Django 3.1.4 on 2020-12-17 20:10

import apps.customUser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='full_name',
            field=models.CharField(help_text='Optional. Please give your full name. 150 characters or less. Letters and whitespaces only.', max_length=150, validators=[apps.customUser.validators.UnicodeFullNameValidator()], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or less. Letters, digits, @/./+/-/_ only.', max_length=150, unique=True, validators=[apps.customUser.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
