# Generated by Django 3.1.2 on 2020-11-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(verbose_name='Enddatum')),
                ('title', models.CharField(max_length=150, verbose_name='Titel')),
                ('info_text', models.CharField(max_length=2048, verbose_name='Beschreibung')),
                ('token', models.CharField(max_length=32, verbose_name='Token für url')),
                ('multiple_votes', models.BooleanField(verbose_name='Mehrmals Abstimmen')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_tag', models.CharField(max_length=10, verbose_name='HTML Tag')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='Lesbarer Name')),
            ],
            options={
                'verbose_name': 'QuestionType',
                'verbose_name_plural': 'QuestionTypes',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField(verbose_name='IP-Adresse der Einreichung')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Einsendedatum')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='polls.poll', verbose_name='Umfrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Frage')),
                ('required', models.BooleanField(default=False, verbose_name='benötigt')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.poll', verbose_name='zugehörige Umfrage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questiontype', verbose_name='Fragetyp')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question', verbose_name='zugehörige Frage')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2048, verbose_name='Antwortwert')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.choice', verbose_name='Antwortkey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.question', verbose_name='Frage')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL, verbose_name='Einsendung')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
