# Generated by Django 3.1.2 on 2020-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='html_tag',
        ),
        migrations.AddField(
            model_name='questiontype',
            name='html_type',
            field=models.CharField(default='text', max_length=10, verbose_name='HTML Input Typ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='erforderlich'),
        ),
    ]
