# Generated by Django 3.1.6 on 2021-02-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_squashed_0023_auto_20210129_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(verbose_name='Öffentlich zugänglich'),
        ),
        migrations.AlterField(
            model_name='questiontypeparam',
            name='default',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Standardwert'),
        ),
    ]
