# Generated by Django 3.1.2 on 2020-11-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201125_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='html_type',
            new_name='html_input_type',
        ),
    ]
