# Generated by Django 3.1.6 on 2021-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210207_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='related_questions',
            field=models.ManyToManyField(to='polls.Question', verbose_name='verknüpfte Fragen'),
        ),
    ]
