# Generated by Django 3.1.2 on 2020-12-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201205_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='enable_choices',
            field=models.BooleanField(default=False, verbose_name='Optionen verfügbar'),
        ),
    ]
