# Generated by Django 3.1.6 on 2021-02-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210214_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='related_questions',
        ),
        migrations.AddField(
            model_name='choice',
            name='related_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_choices', to='polls.question', verbose_name='verknüpfte Fragen'),
        ),
    ]
