# Generated by Django 3.1.2 on 2020-12-05 22:14

import apps.polls.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201205_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='form_widget',
            field=models.CharField(help_text='Vollständiger Pfad zu einem Widget z.B. "django.forms.widgets.TextInput".', max_length=255, validators=[apps.polls.validators.FormWidgetValidator()], verbose_name='Django Form Widget Klassen Pfad'),
        ),
    ]
