# Generated by Django 3.1.6 on 2021-02-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210215_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='related_questions',
            new_name='related_question',
        ),
    ]
