# Generated by Django 3.2 on 2021-04-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210216_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='related_question',
        ),
    ]
