# Generated by Django 3.1.4 on 2020-12-16 15:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201214_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 12, 16, 15, 1, 45, 174900, tzinfo=utc), message='The date lies in the past.')], verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 12, 16, 15, 1, 45, 174900, tzinfo=utc), message='The date lies in the past.')], verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='Token für url'),
        ),
    ]
