# Generated by Django 3.2.15 on 2022-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_poll_results_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='results_public',
        ),
        migrations.AddField(
            model_name='question',
            name='results_public',
            field=models.BooleanField(default=False, verbose_name='Ergebnisse öffentlich zugänglich'),
        ),
    ]
