# Generated by Django 3.1.4 on 2020-12-17 20:16

import apps.polls.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20201216_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(apps.polls.models.get_past_date, message='The date lies in the past.')], verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='token',
            field=models.CharField(default=apps.polls.models.get_default_token, max_length=32, unique=True, verbose_name='Token für url'),
        ),
    ]
