# Generated by Django 3.1.4 on 2020-12-18 23:37

import apps.polls.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20201217_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='form_field',
            field=models.CharField(default='django.forms.fields.CharField', help_text='Vollständiger Pfad zu einem Field z.B. "django.forms.fields.CharField".', max_length=255, validators=[apps.polls.validators.FormFieldValidator()], verbose_name='Django Form Field Klassen Pfad'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(related_name='answer', to='polls.Choice', verbose_name='Antwortkey'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='form_widget',
            field=models.CharField(blank=True, help_text='Vollständiger Pfad zu einem Widget z.B. "django.forms.widgets.TextInput".', max_length=255, validators=[apps.polls.validators.FormWidgetValidator()], verbose_name='Django Form Widget Klassen Pfad'),
        ),
    ]
