# Generated by Django 3.1.4 on 2020-12-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20201219_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='html_input_type',
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Antwortwert'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Einsendedatum'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
    ]
