# Generated by Django 3.1.4 on 2020-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201220_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse der Einreichung'),
        ),
    ]
