# Generated by Django 3.1.4 on 2020-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20201221_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich zugänglich'),
            preserve_default=False,
        ),
    ]
