# Generated by Django 3.1.5 on 2021-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210124_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Parameter Name')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='Lesbarer Name, wird dem Nutzer angezeigt')),
                ('default', models.CharField(max_length=128, verbose_name='Standradwert')),
                ('val_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Decimal')], max_length=128, verbose_name='Typ der Eingabewerte')),
                ('question_type', models.ManyToManyField(related_name='params', to='polls.QuestionType', verbose_name='Zugehöriger Frage Typ')),
            ],
            options={
                'verbose_name': 'QuestionTypeParam',
                'verbose_name_plural': 'QuestionTypeParams',
            },
        ),
    ]
