# Generated by Django 3.1.5 on 2021-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_questiontypeparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra Parameter für Frage'),
        ),
    ]
