# Generated by Django 3.1.5 on 2021-01-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_question_extra_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontypeparam',
            name='default',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Standradwert'),
        ),
    ]
